org.gradle.jvmargs=-Xmx2G

minecraft_version=26.2
minecraft_version_range=[26.2,26.3)
forge_version=26.2-65.1.3
forge_version_range=[65,)
loader_version_range=[65,)
mapping_channel=official
mapping_version=26.2

mod_id=pingdisplayoverlay
mod_name=Ping Display+Overlay
mod_license=MIT
mod_version=1.3.0
mod_group_id=com.pingdisplayoverlay
mod_authors=Somersault41
mod_description=Customizable ping display and player heads in the tab list and HUD.
